# Generated by Django 4.0.6 on 2022-07-20 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('pid', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.TextField(max_length=30)),
                ('desc', models.TextField(max_length=2000)),
                ('price', models.FloatField()),
                ('weight', models.FloatField()),
                ('category', models.TextField(max_length=10)),
                ('delivery', models.SmallIntegerField(default=7)),
                ('stock', models.BooleanField(default=True)),
                ('image', models.ImageField(upload_to='upload')),
            ],
        ),
    ]
